apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      runtimeClassName: nvidia
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1  
        env:
        - name: OLLAMA_GPU
          value: "true"
        - name: OLLAMA_NUM_GPU
          value: "1"
        - name: OLLAMA_MODELS
          value: "/home/ollama/models"          
        - name: OLLAMA_DEBUG
          value: "false"
        - name: OLLAMA_FLASH_ATTENTION
          value: "false"
        # - name: OLLAMA_API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: ollama-secret
        #       key: api-key      
        volumeMounts:
        - name: ollama-ssh-private
          mountPath: /root/.ollama/id_ed25519
          readOnly: true
        - name: ollama-ssh-public
          mountPath: /root/.ollama/id_ed25519.pub
          readOnly: true
        - name: host-home
          mountPath: /home
      volumes:
      - name: ollama-ssh-private
        hostPath:
          path: /home/ollama/ssh/id_ed25519
          type: File
      - name: ollama-ssh-public
        hostPath:
          path: /home/ollama/ssh/id_ed25519.pub
          type: File
      - name: host-home
        hostPath:
          path: /home
          type: Directory

# kubectl create secret generic ollama-secret --from-literal=api-key="your-api-key"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
spec:
  selector:
    app: ollama
  type: NodePort
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
      nodePort: 31434
